name: pushcube
args: []
kwargs:
  env_id: PushCube-v1
  image_size: 128
  show_goal: true
  control_mode: pd_ee_delta_pos
  reward_mode: dense
  max_episode_steps: 50
  sim_backend: auto
  reconfiguration_freq: 0
  sensor_cam_eye_pos: [0.45, 0.35, 0.25]
  sensor_cam_target_pos: [0.0, 0.0, 0.1]

dataset:
  _target_: datasets.pickcube_dset.load_pickcube_slice_train_val
  data_path: ${oc.env:DATASET_DIR}/pushcube_v1
  normalize_action: ${normalize_action}
  split_ratio: 0.9
  transform:
    _target_: datasets.img_transforms.default_transform
    img_size: ${img_size}

decoder_path: null
num_workers: 4
